name: Leo Tong
favicon: null
layout_spectrum: 0.22767124720849097
typography_spectrum: 0.8802539089228958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9525288362056017
  lightness: 0.08127305004745722
  saturation: 0.529699529055506
  rhythmicContrast: 0.3980342943686992
purpose: []
