favicon: null
name: Leo Tong
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8781362
  brandStrength: 1
  lightness: 0.5681003
  brandColors:
    - '#D5D9E4'
    - '#AEB8C2'
    - '#3E637D'
    - '#253C42'
    - '#070B0A'
  rhythmicContrast: 0.3960573
typography_spectrum: 0.8802539089228958
layout_spectrum: 0.227671247208491
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
